pipeline:
  projectIdentifier: CI_NodeJs_Pipeline
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: "Destroy "
        identifier: Destroy
        description: ""
        type: IACM
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          workspace: aws_terraform_ec2_test
          execution:
            steps:
              - step:
                  type: IACMTerraformPlugin
                  name: init
                  identifier: init
                  timeout: 10m
                  spec:
                    command: init
              - step:
                  type: IACMTerraformPlugin
                  name: planDestroy
                  identifier: planDestroy
                  timeout: 10m
                  spec:
                    command: plan-destroy
              - step:
                  type: IACMApproval
                  name: Approve destroy
                  identifier: Approve_destroy
                  spec:
                    autoApprove: false
                  timeout: 1h
              - step:
                  type: IACMTerraformPlugin
                  name: destroy
                  identifier: destroy
                  timeout: 10m
                  spec:
                    command: destroy
        tags: {}
  identifier: Destroy_terraform
  name: Destroy terraform
